# CMake generated Testfile for 
# Source directory: /home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch
# Build directory: /home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_CDOS "ns3.36.1-CDOS-default")
set_tests_properties(ctest-scratch_CDOS PROPERTIES  WORKING_DIRECTORY "/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/build/scratch/" _BACKTRACE_TRIPLES "/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;59;set_runtime_outputdirectory;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;67;create_scratch;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_first "ns3.36.1-first-default")
set_tests_properties(ctest-scratch_first PROPERTIES  WORKING_DIRECTORY "/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/build/scratch/" _BACKTRACE_TRIPLES "/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;59;set_runtime_outputdirectory;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;67;create_scratch;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.36.1-scratch-simulator-default")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/build/scratch/" _BACKTRACE_TRIPLES "/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;59;set_runtime_outputdirectory;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;67;create_scratch;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-simulator-subdir "ns3.36.1-scratch-simulator-subdir-default")
set_tests_properties(ctest-scratch_subdir_scratch-simulator-subdir PROPERTIES  WORKING_DIRECTORY "/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;59;set_runtime_outputdirectory;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;97;create_scratch;/home/vedantmathur/Downloads/ns-allinone-3.36.1/ns-3.36.1/scratch/CMakeLists.txt;0;")
